caldera_members_frontpage_index:
    path:     /
    defaults: { _controller: CalderaMembersBundle:Frontpage:index }

caldera_members_api_user_info:
    path:     /api/user/info
    defaults: { _controller: CalderaMembersBundle:UserApi:info }